# Text generation, content templates, translation, and image enhancement.
# ALL ad text (headline, tagline, features, CTA, descriptions, captions)
# is generated by AI via Pollinations — no hardcoded copy.

import json
import re
import time
from typing import Any, Dict, List, Optional

import numpy as np
import requests
from PIL import Image, ImageEnhance


# ---------------------------------------------------------------------------
# Text Generator (Pollinations.ai - free, no API key)
# ---------------------------------------------------------------------------

class PollinationsTextGenerator:
    URL = "https://text.pollinations.ai/"
    TIMEOUT = 60

    def generate(self, system_prompt: str, user_prompt: str, model: str = "openai") -> Optional[str]:
        try:
            payload = {
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "model": model,
                "seed": int(time.time()) % 10000,
                "jsonMode": False,
            }
            resp = requests.post(self.URL, json=payload, timeout=self.TIMEOUT)
            if resp.status_code == 200 and len(resp.text) > 10:
                return resp.text.strip()
        except Exception:
            pass
        return None

    def generate_json(self, system_prompt: str, user_prompt: str) -> Optional[dict]:
        try:
            payload = {
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "model": "openai",
                "seed": int(time.time()) % 10000,
                "jsonMode": True,
            }
            resp = requests.post(self.URL, json=payload, timeout=self.TIMEOUT)
            if resp.status_code == 200:
                text = resp.text.strip()
                if text.startswith("```"):
                    text = re.sub(r'^```(?:json)?\s*', '', text)
                    text = re.sub(r'\s*```$', '', text)
                return json.loads(text)
        except Exception:
            pass
        return None


# ---------------------------------------------------------------------------
# Content Generator — ALL text is AI-generated via Pollinations
# ---------------------------------------------------------------------------

class ContentGenerator:
    def __init__(self, clip_extractor):
        self.clip = clip_extractor
        self.text_gen = PollinationsTextGenerator()

    def generate_product_content(
        self, brand: str, category: str, subcategory: str,
        features: List[str], tagline: str, query: str
    ) -> Dict[str, Any]:
        """Generate ALL ad content via AI. Falls back to brand name only if AI fails."""
        brand_clean = brand.replace("_", " ")
        sub_clean = subcategory.replace("_", " ") if subcategory else category.replace("_", " ")

        # Extract product type from user query
        product_desc = self._extract_product_from_query(query, brand_clean)
        display_product = product_desc if product_desc else sub_clean

        # Try AI generation for everything
        ai_content = self._generate_all_via_ai(brand_clean, category, display_product, query)
        if ai_content:
            return ai_content

        # Minimal fallback — just brand name, no hardcoded marketing copy
        return {
            "product_title": f"{brand_clean} {display_product.title()}",
            "product_description": f"{brand_clean} {display_product}",
            "instagram_caption": f"{brand_clean} {display_product}",
            "whatsapp_copy": f"{brand_clean} {display_product}",
            "hashtags": [brand_clean.replace(" ", ""), display_product.replace(" ", "")],
            "headline": brand_clean,
            "tagline": "",
            "features": [],
            "cta_text": "",
        }

    def _extract_product_from_query(self, query: str, brand_clean: str) -> str:
        if not query:
            return ""
        desc = query.lower()
        for word in brand_clean.lower().split():
            desc = desc.replace(word, "")
        filler = {"ad", "ads", "advertisement", "pamphlet", "poster", "banner",
                  "create", "make", "generate", "please", "want", "need", "i",
                  "a", "an", "the", "for", "with", "and", "of", "in", "on",
                  "me", "my", "give", "show", "by", "it", "that", "this",
                  "wearing", "worn", "using", "holding", "showing", "displaying",
                  "person", "people", "man", "woman", "women", "men", "model",
                  "models", "girl", "boy", "lady", "ladies"}
        words = [w for w in desc.split() if w not in filler]
        return " ".join(words).strip()

    def _generate_all_via_ai(
        self, brand: str, category: str, product: str, query: str
    ) -> Optional[Dict[str, Any]]:
        """Call Pollinations AI to generate ALL ad text content in one shot."""
        system_prompt = (
            "You are an expert advertising copywriter. Given a brand and product, "
            "generate compelling ad content. Output ONLY valid JSON with these exact keys:\n"
            '{\n'
            '  "headline": "Short catchy headline (3-6 words, no brand name)",\n'
            '  "tagline": "Brand tagline or slogan (3-8 words)",\n'
            '  "features": ["feature 1 (3-5 words)", "feature 2", "feature 3", "feature 4"],\n'
            '  "cta_text": "Call to action (2-3 words, ALL CAPS)",\n'
            '  "product_title": "Full product title with brand",\n'
            '  "product_description": "2-3 sentence product description",\n'
            '  "instagram_caption": "Engaging Instagram caption with emojis",\n'
            '  "whatsapp_copy": "Short WhatsApp promotional message",\n'
            '  "hashtags": ["tag1", "tag2", "tag3", "tag4", "tag5"]\n'
            '}\n'
            "Make ALL text unique, creative, and specific to the product. "
            "Do NOT use generic phrases like 'Premium quality' or 'Explore Now'. "
            "The headline should be punchy and memorable. "
            "Features should describe real product benefits specific to this item. "
            "The CTA should be action-oriented and relevant to the product type."
        )

        user_prompt = (
            f"Brand: {brand}\n"
            f"Category: {category}\n"
            f"Product: {product}\n"
            f"User request: {query}\n"
            f"Generate creative ad content for this product."
        )

        try:
            result = self.text_gen.generate_json(system_prompt, user_prompt)
            if result and isinstance(result, dict):
                # Validate we got the essential fields
                headline = result.get("headline", "")
                features = result.get("features", [])
                cta = result.get("cta_text", "")

                if headline and len(headline) > 2 and features and len(features) >= 2:
                    print(f"  AI content: headline='{headline}', cta='{cta}', features={len(features)}")
                    return {
                        "product_title": result.get("product_title", f"{brand} {product}"),
                        "product_description": result.get("product_description", ""),
                        "instagram_caption": result.get("instagram_caption", ""),
                        "whatsapp_copy": result.get("whatsapp_copy", ""),
                        "hashtags": result.get("hashtags", []),
                        "headline": headline,
                        "tagline": result.get("tagline", ""),
                        "features": features[:6],
                        "cta_text": cta.upper() if cta else "",
                    }
        except Exception as e:
            print(f"  AI content generation failed: {e}")

        # Try plain text fallback (non-JSON)
        try:
            fallback_prompt = (
                "You are an ad copywriter. Write a short catchy headline (3-6 words) "
                "for this product ad. Output ONLY the headline, nothing else.\n\n"
                f"Brand: {brand}, Product: {product}, Category: {category}"
            )
            headline = self.text_gen.generate(
                "Output only a short catchy headline, no quotes, no explanation.",
                fallback_prompt
            )
            if headline and 3 < len(headline) < 60:
                headline = headline.strip('"').strip("'").strip()
                return {
                    "product_title": f"{brand} {product.title()}",
                    "product_description": f"{brand} {product}",
                    "instagram_caption": f"{brand} {product}",
                    "whatsapp_copy": f"{brand} {product}",
                    "hashtags": [brand.replace(" ", "")],
                    "headline": headline,
                    "tagline": "",
                    "features": [],
                    "cta_text": "",
                }
        except Exception:
            pass

        return None

    def generate_ad_content_for_language(
        self, brand: str, category: str, subcategory: str,
        features: List[str], tagline: str, query: str, language: str
    ) -> Optional[Dict[str, str]]:
        """Return None — translations handled by the Translator class."""
        return None


# ---------------------------------------------------------------------------
# Translator (free, no API key)
# ---------------------------------------------------------------------------

class Translator:
    def __init__(self):
        self._translator = None

    def _get_translator(self, source: str, target: str):
        try:
            from deep_translator import GoogleTranslator
            return GoogleTranslator(source=source, target=target)
        except ImportError:
            return None

    def translate(self, text: str, target_lang: str, source_lang: str = "en") -> str:
        if target_lang == source_lang or target_lang == "en":
            return text
        try:
            translator = self._get_translator(source_lang, target_lang)
            if translator:
                return translator.translate(text)
        except Exception:
            pass
        return text

    def translate_content(self, content: Dict[str, str], target_lang: str) -> Dict[str, str]:
        if target_lang == "en":
            return content
        translated = {}
        for key, value in content.items():
            if isinstance(value, str) and value:
                translated[key] = self.translate(value, target_lang)
            elif isinstance(value, list):
                translated[key] = [self.translate(v, target_lang) for v in value if isinstance(v, str)]
            else:
                translated[key] = value
        return translated


# ---------------------------------------------------------------------------
# Image Enhancer (fully local, PIL-based)
# ---------------------------------------------------------------------------

class ImageEnhancer:
    @staticmethod
    def enhance(image: Image.Image, brightness: float = 1.15,
                contrast: float = 1.2, sharpness: float = 1.3,
                color: float = 1.1) -> Image.Image:
        img = image.copy()
        img = ImageEnhance.Brightness(img).enhance(brightness)
        img = ImageEnhance.Contrast(img).enhance(contrast)
        img = ImageEnhance.Sharpness(img).enhance(sharpness)
        img = ImageEnhance.Color(img).enhance(color)
        return img

    @staticmethod
    def auto_enhance(image: Image.Image) -> Image.Image:
        """Smart auto-enhancement based on image analysis."""
        img = image.copy().convert("RGB")
        arr = np.array(img).astype(float)

        mean_brightness = arr.mean() / 255.0
        std_val = arr.std() / 255.0

        brightness = 1.0
        if mean_brightness < 0.4:
            brightness = 1.3
        elif mean_brightness > 0.7:
            brightness = 0.9

        contrast = 1.0
        if std_val < 0.15:
            contrast = 1.4
        elif std_val > 0.35:
            contrast = 0.95

        img = ImageEnhance.Brightness(img).enhance(brightness)
        img = ImageEnhance.Contrast(img).enhance(contrast)
        img = ImageEnhance.Sharpness(img).enhance(1.25)
        img = ImageEnhance.Color(img).enhance(1.1)

        return img
