# Text generation, content templates, translation, and image enhancement.
# ALL ad text (headline, tagline, features, CTA, descriptions, captions)
# is generated by AI — primary: Google Gemini, fallback: Pollinations.

import json
import os
import re
import time
from typing import Any, Dict, List, Optional

import numpy as np
import requests
from PIL import Image, ImageEnhance


# ---------------------------------------------------------------------------
# Text Generator — Google Gemini (primary, fast & reliable)
# ---------------------------------------------------------------------------

class GeminiTextGenerator:
    """Google Gemini API text generator. Requires GOOGLE_API_KEY env var."""

    MODELS = ["gemini-2.0-flash", "gemini-2.0-flash-lite"]
    BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models"
    TIMEOUT = 30

    def __init__(self):
        self.api_key = os.getenv("GOOGLE_API_KEY", "")
        self.available = bool(self.api_key)
        if self.available:
            print(f"      [GEMINI-TEXT] Initialized with API key ({self.api_key[:8]}...)")
        else:
            print(f"      [GEMINI-TEXT] No GOOGLE_API_KEY — Gemini text gen disabled")

    def generate(self, system_prompt: str, user_prompt: str, model: str = None) -> Optional[str]:
        if not self.available:
            return None
        models_to_try = list(self.MODELS)
        if model and model in models_to_try:
            models_to_try.remove(model)
            models_to_try.insert(0, model)

        payload = {
            "contents": [{"parts": [{"text": user_prompt}]}],
            "systemInstruction": {"parts": [{"text": system_prompt}]},
            "generationConfig": {"temperature": 0.9, "maxOutputTokens": 1024},
        }

        for i, m in enumerate(models_to_try):
            if i > 0:
                time.sleep(1)  # Brief delay before retry
            url = f"{self.BASE_URL}/{m}:generateContent?key={self.api_key}"
            try:
                print(f"      [GEMINI-TEXT] Trying {m}...")
                t0 = time.time()
                resp = requests.post(url, json=payload, timeout=self.TIMEOUT)
                elapsed = time.time() - t0
                print(f"      [GEMINI-TEXT] Response: {m} status={resp.status_code} | time={elapsed:.2f}s")
                if resp.status_code == 200:
                    data = resp.json()
                    text = data.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                    if text and len(text) > 5:
                        print(f"      [GEMINI-TEXT] SUCCESS: \"{text[:100]}{'...' if len(text) > 100 else ''}\"")
                        return text.strip()
                elif resp.status_code == 429:
                    print(f"      [GEMINI-TEXT] Rate limited on {m}, trying next...")
                    continue
                else:
                    print(f"      [GEMINI-TEXT] Failed on {m}: {resp.text[:200]}")
            except requests.Timeout:
                print(f"      [GEMINI-TEXT] TIMEOUT on {m}")
            except Exception as e:
                print(f"      [GEMINI-TEXT] ERROR on {m}: {e}")
        return None

    def generate_json(self, system_prompt: str, user_prompt: str) -> Optional[dict]:
        if not self.available:
            return None
        # Ask for JSON output explicitly
        json_system = system_prompt + "\n\nIMPORTANT: Output ONLY valid JSON, no markdown fences, no extra text."
        text = self.generate(json_system, user_prompt)
        if not text:
            return None
        try:
            # Strip markdown code fences if present
            clean = text.strip()
            if clean.startswith("```"):
                clean = re.sub(r'^```(?:json)?\s*', '', clean)
                clean = re.sub(r'\s*```$', '', clean)
            parsed = json.loads(clean)
            print(f"      [GEMINI-JSON] Parsed JSON with {len(parsed)} keys: {list(parsed.keys())}")
            return parsed
        except json.JSONDecodeError as e:
            print(f"      [GEMINI-JSON] JSON parse error: {e}")
            return None


# ---------------------------------------------------------------------------
# Text Generator — Anthropic Claude (reliable fallback)
# ---------------------------------------------------------------------------

class AnthropicTextGenerator:
    """Anthropic Claude API text generator. Requires ANTHROPIC_API_KEY env var."""

    URL = "https://api.anthropic.com/v1/messages"
    MODEL = "claude-haiku-4-5-20251001"
    TIMEOUT = 30

    def __init__(self):
        self.api_key = os.getenv("ANTHROPIC_API_KEY", "")
        self.available = bool(self.api_key)
        if self.available:
            print(f"      [ANTHROPIC-TEXT] Initialized with API key ({self.api_key[:12]}...)")
        else:
            print(f"      [ANTHROPIC-TEXT] No ANTHROPIC_API_KEY — Claude text gen disabled")

    def generate(self, system_prompt: str, user_prompt: str, model: str = None) -> Optional[str]:
        if not self.available:
            return None
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
        payload = {
            "model": model or self.MODEL,
            "max_tokens": 1024,
            "system": system_prompt,
            "messages": [{"role": "user", "content": user_prompt}],
        }
        try:
            print(f"      [ANTHROPIC-TEXT] Trying {payload['model']}...")
            t0 = time.time()
            resp = requests.post(self.URL, json=payload, headers=headers, timeout=self.TIMEOUT)
            elapsed = time.time() - t0
            print(f"      [ANTHROPIC-TEXT] Response: status={resp.status_code} | time={elapsed:.2f}s")
            if resp.status_code == 200:
                data = resp.json()
                text = data.get("content", [{}])[0].get("text", "")
                if text and len(text) > 5:
                    print(f"      [ANTHROPIC-TEXT] SUCCESS: \"{text[:100]}{'...' if len(text) > 100 else ''}\"")
                    return text.strip()
            else:
                print(f"      [ANTHROPIC-TEXT] Failed: {resp.text[:200]}")
        except requests.Timeout:
            print(f"      [ANTHROPIC-TEXT] TIMEOUT")
        except Exception as e:
            print(f"      [ANTHROPIC-TEXT] ERROR: {e}")
        return None

    def generate_json(self, system_prompt: str, user_prompt: str) -> Optional[dict]:
        if not self.available:
            return None
        json_system = system_prompt + "\n\nIMPORTANT: Output ONLY valid JSON, no markdown fences, no extra text."
        text = self.generate(json_system, user_prompt)
        if not text:
            return None
        try:
            clean = text.strip()
            if clean.startswith("```"):
                clean = re.sub(r'^```(?:json)?\s*', '', clean)
                clean = re.sub(r'\s*```$', '', clean)
            parsed = json.loads(clean)
            print(f"      [ANTHROPIC-JSON] Parsed JSON with {len(parsed)} keys: {list(parsed.keys())}")
            return parsed
        except json.JSONDecodeError as e:
            print(f"      [ANTHROPIC-JSON] JSON parse error: {e}")
            return None


# ---------------------------------------------------------------------------
# Text Generator — Groq (free, fast LPU inference, no credit card needed)
# Sign up at https://console.groq.com to get a free API key
# ---------------------------------------------------------------------------

class GroqTextGenerator:
    """Groq API text generator. Free tier: 30 RPM, very fast inference."""

    URL = "https://api.groq.com/openai/v1/chat/completions"
    MODELS = ["llama-3.3-70b-versatile", "llama-3.1-8b-instant"]
    TIMEOUT = 30

    def __init__(self):
        self.api_key = os.getenv("GROQ_API_KEY", "")
        self.available = bool(self.api_key)
        if self.available:
            print(f"      [GROQ-TEXT] Initialized with API key ({self.api_key[:8]}...)")
        else:
            print(f"      [GROQ-TEXT] No GROQ_API_KEY — Groq text gen disabled")

    def generate(self, system_prompt: str, user_prompt: str, model: str = None) -> Optional[str]:
        if not self.available:
            return None
        models_to_try = list(self.MODELS)
        if model and model in models_to_try:
            models_to_try.remove(model)
            models_to_try.insert(0, model)

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        for m in models_to_try:
            payload = {
                "model": m,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "temperature": 0.9,
                "max_tokens": 1024,
            }
            try:
                print(f"      [GROQ-TEXT] Trying {m}...")
                t0 = time.time()
                resp = requests.post(self.URL, json=payload, headers=headers, timeout=self.TIMEOUT)
                elapsed = time.time() - t0
                print(f"      [GROQ-TEXT] Response: {m} status={resp.status_code} | time={elapsed:.2f}s")
                if resp.status_code == 200:
                    data = resp.json()
                    text = data.get("choices", [{}])[0].get("message", {}).get("content", "")
                    if text and len(text) > 5:
                        print(f"      [GROQ-TEXT] SUCCESS: \"{text[:100]}{'...' if len(text) > 100 else ''}\"")
                        return text.strip()
                elif resp.status_code == 429:
                    print(f"      [GROQ-TEXT] Rate limited on {m}, trying next...")
                    continue
                else:
                    print(f"      [GROQ-TEXT] Failed on {m}: {resp.text[:200]}")
            except requests.Timeout:
                print(f"      [GROQ-TEXT] TIMEOUT on {m}")
            except Exception as e:
                print(f"      [GROQ-TEXT] ERROR on {m}: {e}")
        return None

    def generate_json(self, system_prompt: str, user_prompt: str) -> Optional[dict]:
        if not self.available:
            return None
        # Groq supports JSON mode via response_format
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        json_system = system_prompt + "\n\nIMPORTANT: Output ONLY valid JSON, no markdown fences, no extra text."
        for m in self.MODELS:
            payload = {
                "model": m,
                "messages": [
                    {"role": "system", "content": json_system},
                    {"role": "user", "content": user_prompt},
                ],
                "temperature": 0.7,
                "max_tokens": 1024,
                "response_format": {"type": "json_object"},
            }
            try:
                print(f"      [GROQ-JSON] Trying {m} with JSON mode...")
                t0 = time.time()
                resp = requests.post(self.URL, json=payload, headers=headers, timeout=self.TIMEOUT)
                elapsed = time.time() - t0
                print(f"      [GROQ-JSON] Response: {m} status={resp.status_code} | time={elapsed:.2f}s")
                if resp.status_code == 200:
                    data = resp.json()
                    text = data.get("choices", [{}])[0].get("message", {}).get("content", "")
                    if text:
                        parsed = json.loads(text)
                        print(f"      [GROQ-JSON] SUCCESS: Parsed JSON with {len(parsed)} keys: {list(parsed.keys())}")
                        return parsed
                elif resp.status_code == 429:
                    print(f"      [GROQ-JSON] Rate limited on {m}, trying next...")
                    continue
                else:
                    print(f"      [GROQ-JSON] Failed on {m}: {resp.text[:200]}")
            except json.JSONDecodeError as e:
                print(f"      [GROQ-JSON] JSON parse error on {m}: {e}")
            except requests.Timeout:
                print(f"      [GROQ-JSON] TIMEOUT on {m}")
            except Exception as e:
                print(f"      [GROQ-JSON] ERROR on {m}: {e}")
        return None


# ---------------------------------------------------------------------------
# Text Generator — Pollinations.ai (free fallback, no API key)
# ---------------------------------------------------------------------------

class PollinationsTextGenerator:
    URL = "https://text.pollinations.ai/"
    TIMEOUT = 180  # Pollinations is slow but free — give it enough time

    def generate(self, system_prompt: str, user_prompt: str, model: str = "openai") -> Optional[str]:
        print(f"      [POLLINATIONS-TEXT] Plain text generation request")
        print(f"      [POLLINATIONS-TEXT] URL: {self.URL}")
        print(f"      [POLLINATIONS-TEXT] Model: {model}")
        print(f"      [POLLINATIONS-TEXT] Timeout: {self.TIMEOUT}s")
        print(f"      [POLLINATIONS-TEXT] System prompt: {system_prompt[:80]}...")
        print(f"      [POLLINATIONS-TEXT] User prompt: {user_prompt[:80]}...")
        try:
            seed = int(time.time()) % 10000
            payload = {
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "model": model,
                "seed": seed,
                "jsonMode": False,
            }
            print(f"      [POLLINATIONS-TEXT] Seed: {seed} | jsonMode: False")
            t0 = time.time()
            resp = requests.post(self.URL, json=payload, timeout=self.TIMEOUT)
            elapsed = time.time() - t0
            print(f"      [POLLINATIONS-TEXT] Response: status={resp.status_code} | size={len(resp.text)} chars | time={elapsed:.2f}s")
            if resp.status_code == 200 and len(resp.text) > 10:
                result = resp.text.strip()
                print(f"      [POLLINATIONS-TEXT] SUCCESS: \"{result[:100]}{'...' if len(result) > 100 else ''}\"")
                return result
            else:
                print(f"      [POLLINATIONS-TEXT] FAILED: status={resp.status_code}, response too short ({len(resp.text)} chars)")
        except requests.Timeout:
            print(f"      [POLLINATIONS-TEXT] TIMEOUT after {self.TIMEOUT}s")
        except Exception as e:
            print(f"      [POLLINATIONS-TEXT] ERROR: {e}")
        return None

    def generate_json(self, system_prompt: str, user_prompt: str) -> Optional[dict]:
        print(f"      [POLLINATIONS-JSON] JSON generation request")
        print(f"      [POLLINATIONS-JSON] URL: {self.URL}")
        print(f"      [POLLINATIONS-JSON] Model: openai")
        print(f"      [POLLINATIONS-JSON] Timeout: {self.TIMEOUT}s")
        try:
            seed = int(time.time()) % 10000
            payload = {
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                "model": "openai",
                "seed": seed,
                "jsonMode": True,
            }
            print(f"      [POLLINATIONS-JSON] Seed: {seed} | jsonMode: True")
            t0 = time.time()
            resp = requests.post(self.URL, json=payload, timeout=self.TIMEOUT)
            elapsed = time.time() - t0
            print(f"      [POLLINATIONS-JSON] Response: status={resp.status_code} | size={len(resp.text)} chars | time={elapsed:.2f}s")
            if resp.status_code == 200:
                text = resp.text.strip()
                if text.startswith("```"):
                    print(f"      [POLLINATIONS-JSON] Stripping markdown code fences from response")
                    text = re.sub(r'^```(?:json)?\s*', '', text)
                    text = re.sub(r'\s*```$', '', text)
                parsed = json.loads(text)
                print(f"      [POLLINATIONS-JSON] SUCCESS: Parsed JSON with {len(parsed)} keys: {list(parsed.keys())}")
                return parsed
            else:
                print(f"      [POLLINATIONS-JSON] FAILED: status={resp.status_code}")
        except json.JSONDecodeError as e:
            print(f"      [POLLINATIONS-JSON] JSON PARSE ERROR: {e}")
        except requests.Timeout:
            print(f"      [POLLINATIONS-JSON] TIMEOUT after {self.TIMEOUT}s")
        except Exception as e:
            print(f"      [POLLINATIONS-JSON] ERROR: {e}")
        return None


# ---------------------------------------------------------------------------
# Content Generator — ALL text is AI-generated via Pollinations
# ---------------------------------------------------------------------------

class ContentGenerator:
    def __init__(self, clip_extractor):
        self.clip = clip_extractor
        self.gemini_gen = GeminiTextGenerator()
        self.groq_gen = GroqTextGenerator()
        self.anthropic_gen = AnthropicTextGenerator()
        self.pollinations_gen = PollinationsTextGenerator()
        available = [n for n, g in [("Gemini", self.gemini_gen), ("Groq", self.groq_gen), ("Anthropic", self.anthropic_gen)] if g.available]
        print(f"    [CONTENT-GEN] ContentGenerator initialized — Chain: {' -> '.join(available + ['Pollinations'])}")

    def generate_product_content(
        self, brand: str, category: str, subcategory: str,
        features: List[str], tagline: str, query: str,
        product_metadata: dict = None,
    ) -> Dict[str, Any]:
        """Generate ALL ad content via AI. Falls back to brand name only if AI fails."""
        brand_clean = brand.replace("_", " ")
        sub_clean = subcategory.replace("_", " ") if subcategory else category.replace("_", " ")

        # Extract product type from user query
        product_desc = self._extract_product_from_query(query, brand_clean)
        display_product = product_desc if product_desc else sub_clean
        print(f"    [CONTENT-GEN] Extracted product: \"{display_product}\" from query: \"{query[:100]}\"")

        # Build structured product info from metadata for better AI prompts
        product_details = self._build_product_details(product_metadata) if product_metadata else ""

        # Try AI generation for everything
        print(f"    [CONTENT-GEN] Attempting AI generation (Pollinations openai model)...")
        ai_content = self._generate_all_via_ai(brand_clean, category, display_product, query, product_details)
        if ai_content:
            print(f"    [CONTENT-GEN] SUCCESS: AI-generated content with {len(ai_content)} fields")
            return ai_content

        # Minimal fallback — just brand name, no hardcoded marketing copy
        print(f"    [CONTENT-GEN] FALLBACK: AI generation failed! Using minimal brand-only content")
        print(f"    [CONTENT-GEN] FALLBACK: No hardcoded marketing copy — only brand name used")
        return {
            "product_title": f"{brand_clean} {display_product.title()}",
            "product_description": f"{brand_clean} {display_product}",
            "instagram_caption": f"{brand_clean} {display_product}",
            "whatsapp_copy": f"{brand_clean} {display_product}",
            "hashtags": [brand_clean.replace(" ", ""), display_product.replace(" ", "")],
            "headline": brand_clean,
            "tagline": "",
            "features": [],
            "cta_text": "",
        }

    def _build_product_details(self, metadata: dict) -> str:
        """Build a clean product details string from structured metadata fields."""
        lines = []
        field_map = {
            "product_name": "Product Name",
            "product_type": "Product Type",
            "material": "Material",
            "color": "Color",
            "key_features": "Key Features",
            "target_audience": "Target Audience",
            "occasion": "Occasion",
            "pack_size": "Pack Size",
            "size_range": "Size Range",
            "flavor": "Flavor",
            "price": "Price",
            "scene_description": "Scene",
        }
        for key, label in field_map.items():
            val = metadata.get(key, "")
            if val and str(val).strip():
                lines.append(f"{label}: {val}")
        return "\n".join(lines)

    def _extract_product_from_query(self, query: str, brand_clean: str) -> str:
        if not query:
            return ""
        desc = query.lower()
        for word in brand_clean.lower().split():
            desc = desc.replace(word, "")
        filler = {"ad", "ads", "advertisement", "pamphlet", "poster", "banner",
                  "create", "make", "generate", "please", "want", "need", "i",
                  "a", "an", "the", "for", "with", "and", "of", "in", "on",
                  "me", "my", "give", "show", "by", "it", "that", "this",
                  "wearing", "worn", "using", "holding", "showing", "displaying",
                  "person", "people", "man", "woman", "women", "men", "model",
                  "models", "girl", "boy", "lady", "ladies"}
        words = [w for w in desc.split() if w not in filler]
        return " ".join(words).strip()

    def _generate_all_via_ai(
        self, brand: str, category: str, product: str, query: str,
        product_details: str = "",
    ) -> Optional[Dict[str, Any]]:
        """Call Pollinations AI to generate ALL ad text content in one shot."""
        print(f"    [AI-CONTENT] Attempting full JSON content generation...")
        print(f"    [AI-CONTENT] Brand: {brand} | Category: {category} | Product: {product}")
        system_prompt = (
            "You are an expert advertising copywriter. Given a brand and product, "
            "generate compelling, creative ad content. Output ONLY valid JSON with these exact keys:\n"
            '{\n'
            '  "headline": "Short catchy headline (3-6 words, no brand name)",\n'
            '  "tagline": "Brand tagline or slogan (3-8 words)",\n'
            '  "features": ["feature 1 (3-5 words)", "feature 2", "feature 3", "feature 4"],\n'
            '  "cta_text": "Call to action (2-3 words, ALL CAPS)",\n'
            '  "product_title": "Full product title with brand",\n'
            '  "product_description": "2-3 sentence product description",\n'
            '  "instagram_caption": "Engaging Instagram caption with emojis",\n'
            '  "whatsapp_copy": "Short WhatsApp promotional message",\n'
            '  "hashtags": ["tag1", "tag2", "tag3", "tag4", "tag5"]\n'
            '}\n\n'
            "CRITICAL RULES:\n"
            "- Write ORIGINAL creative marketing copy. Do NOT repeat the raw input data.\n"
            "- Do NOT include pipe characters (|) or field labels like 'material:', 'color:' in your output.\n"
            "- The product_title should be a clean, marketable title (e.g. 'Tejasvi 22K Gold Bangles Set by Kalyan Jewellers').\n"
            "- The product_description should be 2-3 flowing sentences describing the product's appeal.\n"
            "- The instagram_caption should be engaging with emojis and a storytelling hook.\n"
            "- The whatsapp_copy should be a concise promotional message.\n"
            "- Hashtags should be short, relevant single words or phrases (e.g. 'GoldJewellery', 'WeddingBangles').\n"
            "- Make ALL text unique, creative, and specific to the product.\n"
            "- The headline should be punchy and memorable.\n"
            "- Features should describe real product benefits specific to this item.\n"
            "- The CTA should be action-oriented and relevant to the product type."
        )

        # Build a clean user prompt — use structured details if available
        user_parts = [f"Brand: {brand}", f"Category: {category}", f"Product: {product}"]
        if product_details:
            user_parts.append(f"\nProduct Details:\n{product_details}")
        else:
            user_parts.append(f"User request: {query}")
        user_parts.append("\nGenerate creative, compelling ad content for this product.")
        user_prompt = "\n".join(user_parts)

        # Try generators in order: Gemini -> Groq -> Anthropic -> Pollinations
        generators = []
        if self.gemini_gen.available:
            generators.append(("Gemini", self.gemini_gen))
        if self.groq_gen.available:
            generators.append(("Groq", self.groq_gen))
        if self.anthropic_gen.available:
            generators.append(("Anthropic", self.anthropic_gen))
        generators.append(("Pollinations", self.pollinations_gen))

        for gen_name, gen in generators:
            try:
                print(f"    [AI-CONTENT] Trying {gen_name} JSON API...")
                result = gen.generate_json(system_prompt, user_prompt)
                if result and isinstance(result, dict):
                    headline = result.get("headline", "")
                    features = result.get("features", [])
                    cta = result.get("cta_text", "")

                    if headline and len(headline) > 2 and features and len(features) >= 2:
                        print(f"    [AI-CONTENT] {gen_name} JSON SUCCESS!")
                        print(f"    [AI-CONTENT] headline='{headline}' | cta='{cta}' | features={len(features)}")
                        return {
                            "product_title": result.get("product_title", f"{brand} {product}"),
                            "product_description": result.get("product_description", ""),
                            "instagram_caption": result.get("instagram_caption", ""),
                            "whatsapp_copy": result.get("whatsapp_copy", ""),
                            "hashtags": result.get("hashtags", []),
                            "headline": headline,
                            "tagline": result.get("tagline", ""),
                            "features": features[:6],
                            "cta_text": cta.upper() if cta else "",
                        }
                    else:
                        print(f"    [AI-CONTENT] {gen_name} JSON incomplete: headline='{headline}', features={len(features)}")
                else:
                    print(f"    [AI-CONTENT] {gen_name} JSON returned None or non-dict")
            except Exception as e:
                print(f"    [AI-CONTENT] {gen_name} JSON FAILED: {e}")

        # Try plain text headline as last resort (try each generator)
        print(f"    [AI-CONTENT] FALLBACK: Trying plain text headline generation...")
        fallback_prompt = (
            "You are an ad copywriter. Write a short catchy headline (3-6 words) "
            "for this product ad. Output ONLY the headline, nothing else.\n\n"
            f"Brand: {brand}, Product: {product}, Category: {category}"
        )
        for gen_name, gen in generators:
            try:
                headline = gen.generate(
                    "Output only a short catchy headline, no quotes, no explanation.",
                    fallback_prompt
                )
                if headline and 3 < len(headline) < 60:
                    headline = headline.strip('"').strip("'").strip()
                    print(f"    [AI-CONTENT] {gen_name} plain text headline SUCCESS: \"{headline}\"")
                    return {
                        "product_title": f"{brand} {product.title()}",
                        "product_description": f"{brand} {product}",
                        "instagram_caption": f"{brand} {product}",
                        "whatsapp_copy": f"{brand} {product}",
                        "hashtags": [brand.replace(" ", "")],
                        "headline": headline,
                        "tagline": "",
                        "features": [],
                        "cta_text": "",
                    }
                else:
                    print(f"    [AI-CONTENT] {gen_name} headline invalid: \"{headline}\"")
            except Exception as e:
                print(f"    [AI-CONTENT] {gen_name} headline FAILED: {e}")

        print(f"    [AI-CONTENT] ALL AI generation attempts failed! Returning None")
        return None

    def generate_ad_content_for_language(
        self, brand: str, category: str, subcategory: str,
        features: List[str], tagline: str, query: str, language: str
    ) -> Optional[Dict[str, str]]:
        """Return None — translations handled by the Translator class."""
        print(f"    [CONTENT-GEN] generate_ad_content_for_language({language}) -> None (handled by Translator)")
        return None


# ---------------------------------------------------------------------------
# Translator (free, no API key)
# ---------------------------------------------------------------------------

class Translator:
    def __init__(self):
        self._translator = None
        print(f"    [TRANSLATOR] Translator initialized (engine: GoogleTranslator via deep_translator)")
        print(f"    [TRANSLATOR] Cost: FREE | No API key required")

    def _get_translator(self, source: str, target: str):
        try:
            from deep_translator import GoogleTranslator
            return GoogleTranslator(source=source, target=target)
        except ImportError:
            print(f"    [TRANSLATOR] ERROR: deep_translator not installed!")
            return None

    def translate(self, text: str, target_lang: str, source_lang: str = "en") -> str:
        if target_lang == source_lang or target_lang == "en":
            return text
        try:
            translator = self._get_translator(source_lang, target_lang)
            if translator:
                t0 = time.time()
                result = translator.translate(text)
                elapsed = time.time() - t0
                print(f"      [TRANSLATE] {source_lang}->{target_lang} | {len(text)} chars -> {len(result)} chars | {elapsed:.2f}s")
                return result
            else:
                print(f"      [TRANSLATE] No translator available for {source_lang}->{target_lang}")
        except Exception as e:
            print(f"      [TRANSLATE] FAILED {source_lang}->{target_lang}: {e}")
        return text

    def translate_content(self, content: Dict[str, str], target_lang: str) -> Dict[str, str]:
        if target_lang == "en":
            return content
        print(f"    [TRANSLATOR] Translating content dict ({len(content)} keys) to {target_lang}")
        translated = {}
        for key, value in content.items():
            if isinstance(value, str) and value:
                translated[key] = self.translate(value, target_lang)
            elif isinstance(value, list):
                translated[key] = [self.translate(v, target_lang) for v in value if isinstance(v, str)]
            else:
                translated[key] = value
        print(f"    [TRANSLATOR] Content translation complete: {len(translated)} keys translated")
        return translated


# ---------------------------------------------------------------------------
# Image Enhancer (fully local, PIL-based)
# ---------------------------------------------------------------------------

class ImageEnhancer:
    @staticmethod
    def enhance(image: Image.Image, brightness: float = 1.15,
                contrast: float = 1.2, sharpness: float = 1.3,
                color: float = 1.1) -> Image.Image:
        print(f"    [ENHANCER] Manual enhancement: brightness={brightness}, contrast={contrast}, sharpness={sharpness}, color={color}")
        print(f"    [ENHANCER] Input: {image.size} | Mode: {image.mode}")
        img = image.copy()
        img = ImageEnhance.Brightness(img).enhance(brightness)
        img = ImageEnhance.Contrast(img).enhance(contrast)
        img = ImageEnhance.Sharpness(img).enhance(sharpness)
        img = ImageEnhance.Color(img).enhance(color)
        print(f"    [ENHANCER] Enhancement applied successfully")
        return img

    @staticmethod
    def auto_enhance(image: Image.Image) -> Image.Image:
        """Smart auto-enhancement based on image analysis."""
        print(f"    [ENHANCER] Auto-enhancement starting...")
        print(f"    [ENHANCER] Input: {image.size} | Mode: {image.mode}")
        img = image.copy().convert("RGB")
        arr = np.array(img).astype(float)

        mean_brightness = arr.mean() / 255.0
        std_val = arr.std() / 255.0
        print(f"    [ENHANCER] Image analysis: mean_brightness={mean_brightness:.3f}, std_deviation={std_val:.3f}")

        brightness = 1.0
        if mean_brightness < 0.4:
            brightness = 1.3
            print(f"    [ENHANCER] Image is dark (brightness={mean_brightness:.3f} < 0.4) -> boosting to {brightness}")
        elif mean_brightness > 0.7:
            brightness = 0.9
            print(f"    [ENHANCER] Image is bright (brightness={mean_brightness:.3f} > 0.7) -> reducing to {brightness}")
        else:
            print(f"    [ENHANCER] Brightness OK ({mean_brightness:.3f}) -> no adjustment")

        contrast = 1.0
        if std_val < 0.15:
            contrast = 1.4
            print(f"    [ENHANCER] Low contrast (std={std_val:.3f} < 0.15) -> boosting to {contrast}")
        elif std_val > 0.35:
            contrast = 0.95
            print(f"    [ENHANCER] High contrast (std={std_val:.3f} > 0.35) -> reducing to {contrast}")
        else:
            print(f"    [ENHANCER] Contrast OK ({std_val:.3f}) -> no adjustment")

        img = ImageEnhance.Brightness(img).enhance(brightness)
        img = ImageEnhance.Contrast(img).enhance(contrast)
        img = ImageEnhance.Sharpness(img).enhance(1.25)
        img = ImageEnhance.Color(img).enhance(1.1)
        print(f"    [ENHANCER] Final: brightness={brightness}, contrast={contrast}, sharpness=1.25, color=1.1")

        return img
